services:
  stay-api:
    build:
      context: .
      dockerfile: apps/stay-api/Dockerfile
    container_name: stay-api
    ports:
      - '${API_PORT:-3333}:${API_PORT:-3333}'
    environment:
      - NODE_ENV=production
      - PORT=${API_PORT:-3333}
    volumes:
      - api-data:/app/data
      - api-logs:/app/logs
    restart: unless-stopped

  stay-fe:
    build:
      context: .
      dockerfile: apps/stay-fe/Dockerfile
    container_name: stay-fe
    ports:
      - '${FE_PORT:-3000}:${FE_PORT:-3000}'
    environment:
      - NODE_ENV=production
      - PORT=${FE_PORT:-3000}
    volumes:
      - fe-public:/app/public
      - fe-cache:/app/.next/cache
    restart: unless-stopped
    depends_on:
      - stay-api

volumes:
  api-data:
    name: stay-api-data
  api-logs:
    name: stay-api-logs
  fe-public:
    name: stay-fe-public
  fe-cache:
    name: stay-fe-cache
