import { UIProvider } from '@smart-connection-monorepo/ui-theme';
import themeToken from '@smart-connection-monorepo/ui-theme/theme-token/stay-fe.json';
import '@/styles/index.css';

export const metadata = {
  title: 'Welcome to stay-fe',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UIProvider config={themeToken.variants}>{children}</UIProvider>
      </body>
    </html>
  );
}
