name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile

      - name: Validate all commits from PR
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Debug ESLint config
        run: |
          echo "Checking ESLint config files:"
          ls -la .eslintrc.json || echo "Root ESLint config not found"
          ls -la apps/stay-fe/.eslintrc.json || echo "Stay-fe ESLint config not found"
          ls -la libs/ui-components/.eslintrc.json || echo "UI components ESLint config not found"
          ls -la libs/ui-theme/.eslintrc.json || echo "UI theme ESLint config not found"

      - name: Fix ESLint configuration
        run: |
          chmod +x ./fix-eslint.sh
          ./fix-eslint.sh

      - name: Lint
        run: pnpm exec nx affected -t lint --skip-nx-cache

      - name: Build
        run: pnpm exec nx affected -t build
